grpc:
  server:
    port: 50055

server:
  port: 8081
spring:
  application:
    name: location
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:location-db
      username: sa
      password: password
      driverClassName: org.h2.Driver